### ISSUE TITLE
Inconsistancy between md highlighting and preview

### ISSUE THREAD

**Issue by pcd444** [microsoft/vscode-markdown-tm-grammar#121]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Create md file
2. paste following
ab|cd
--|--
ef\\\\\\\\| |gh
3. open preview
4. Observe difference between highlighting and preview

[highlighting](https://imgur.com/a/iV4J8N4)
[preview](https://imgur.com/a/DdoUdiL)

As you can see the highlighting makes it seem like there should be two raw backslash characters, but in the preview there is only one and one of the vertical slash characters has been escaped. I don't know which is right but they should agree.

Also other md renderers do it a different way.

**Comment by mjbvz** [comment]
This falls under #125. We don't parse tables at all right now

Closing in favor of that issue
