### ISSUE TITLE
Syntax highlighting does not work if text is preceeded by a Tab character or at least 4 spaces

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/vscode-markdown-tm-grammar#123]
````
   **Works (3 spaces)**

   > Works (3  spaces)

	**Does not work (tab).**

	> Does not work (tab)

    **Does not work  (4 spaces**
````

![Screenshot_2022-11-11_09-08-07](https://user-images.githubusercontent.com/22261988/201296663-3a444d06-7362-4cc4-8370-7c05395faf15.png)

**Comment by mjbvz** [comment]
Adding 4 spaces (or a tab) creates a bare code block: https://www.markdownguide.org/basic-syntax#code-blocks
