### ISSUE TITLE
shell codeblocks do not match syntax highlight for a .sh file.

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode-markdown-tm-grammar#156]
Consider this basic shell file:

![image](https://github.com/microsoft/vscode-markdown-tm-grammar/assets/150152/4b01cd92-25aa-4fc0-8d98-3178bd838bb6)

The bash file is syntax highlighted correctly, but when the same context is embedded in markdown the syntax highlighting fails.

**Comment by RedCMD** [comment]
this issue should be moved to the https://github.com/jeff-hykin/better-shell-syntax repo

**Comment by a-stewart** [comment]
The thing is the syntax highlighting is fine in a shell file, it is only when it is embedded in markdown that it becomes an issue.

**Comment by RedCMD** [comment]
yes
but it's still up to the shell author to fix
there's not much Markdown can do, if anything to fix it

**Comment by mjbvz** [comment]
Yes typically issues with embedded grammars are caused by incorrect use of `$base`  or `$self` in the grammar. We can't fix that here

Please move this issue over to the shell grammar so they can investigate
