### ISSUE TITLE
Inside of multiline math expressions in markdown files is not recognized as math/latex context.

### ISSUE THREAD

**Issue by adusamr** [microsoft/vscode-markdown-tm-grammar#161]
This is copied from https://github.com/microsoft/vscode/issues/202450#issue-2080766472

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.1
- OS Version: Windows 11

In markdown file, multiline math expressions like the following are valid and supported by the official markdown preview feature.
But the inside of the dollar signs is not recognized as math/latex context unless the beginning dollar sign is at the start of the line.
I checked the context by "Inspect Editor Tokens and Scopes".
```
aaa $\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}$ bbb
```
I have a lot of latex snippets for writing math expressions in markdown, but they are not suggested in such expressions for this issue.

btw, I have a setting "markdown.preview.breaks": true.
When this is true, I think the only way to write an inline multiline math expression is like this.

**Comment by adusamr** [comment]
I'm replying to https://github.com/microsoft/vscode/issues/202450#issuecomment-2121715754

I checked https://github.com/microsoft/vscode/blob/0dba492e01c5ca1afff8a9de94ba6d8d29ea019f/extensions/vscode-colorize-tests/test/colorize-fixtures/md-math.md#L0-L1

It seems there are some conditions for two dollar signs to be recognized as an inline math expression by the official markdown preview feature:

- No empty line between two dollar signs
- The character before the opening dollar sign is not one of [a-zA-Z0-9] (start of file or \n is allowed)
- The character after the closing dollar sign is not one of [a-zA-Z0-9] (end of file or \n is allowed)

The third one is stated in the above md-math.md: "Should allow inline code to be followed by non word character #136584"
But second one is also necessary.

**Comment by mjbvz** [comment]
The math part of the grammar actually lives in the main VS Code repo so let's track this back in the original issue
