### ISSUE TITLE
Markdown Link Highlighting (references)

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-markdown-tm-grammar#2]
_From @erichiller on February 11, 2017 19:33_

- VSCode Version: 1.9.1
- OS Version: Win 10x64

When defining links such as the below, while in the editor, the links are not highlighted as they are in [test](url) style links. I think it would be better, and more uniform for the editor to highlight these links in the same manner.

```
[Promise] objects have a [then]

[Promise]: https://msdn.microsoft.com/library/windows/apps/BR211867
[then]: https://msdn.microsoft.com/library/windows/apps/BR229728
```

[Promise] objects have a [then]

[Promise]: https://msdn.microsoft.com/library/windows/apps/BR211867
[then]: https://msdn.microsoft.com/library/windows/apps/BR229728

![image](https://cloud.githubusercontent.com/assets/5379325/22856792/a389ea94-f04d-11e6-8090-156019108a57.png)

_Copied from original issue: Microsoft/vscode#20483_

**Comment by mjbvz** [comment]
_From @hashhar on February 15, 2017 3:47_

Is there a better way to implement it other than looking for all unmatched and unescaped square brackets and then referencing them. Also, what code is responsible for the link generation? Does it come from the syntax file or is it generated by modifying an object that holds the viewstate of the editor.

**Comment by mjbvz** [comment]
@hashhar For the syntax highlighting, we should just update the grammar file to identify contents inside of `[...]` as links. To get started, take a look `link-ref` in the syntax file: https://github.com/Microsoft/vscode/blob/master/extensions/markdown/syntaxes/markdown.tmLanguage

**Comment by mjbvz** [comment]
_From @hashhar on March 2, 2017 11:49_

Wow. This got out of hand for me. I'm very confused. Somebody else can and should work on it.

**Comment by mjbvz** [comment]
_From @chirag64 on March 2, 2017 12:43_

I'd like to give this a try.

@erichiller Can you please explain how you want these links to be highlighted? Your link to test style links gives a 404 error.

**Comment by mjbvz** [comment]
Fixed by 2544443db4402b3271b1b99bd9a1efb2c757c3d5

**Comment by rbolsius** [comment]
I believe that the fix for [2544443](https://github.com/Microsoft/vscode-markdown-tm-grammar/commit/2544443db4402b3271b1b99bd9a1efb2c757c3d5) has broken the syntax highlighting for link reference definitions that contain characters other than alphanumeric and underscore.  For example, it is common for a link reference to use hyphens, but hyphens are not matched by `\w`.

```
 (\[)([\w ]+?)(\])(:)    # Reference name
```

So, a link reference definition like the following is no longer highlighted correctly in VS Code.

```markdown
[link][ref-1]

[ref-1]: http://localhost/
```

The link reference definitions were highlighted correctly when the pattern was `(\[)(.+?)(\])(:)    # Reference name`.

Probably it would be better to replace `[\w ]` with `[^]]` to match any character except a closing bracket.

**Comment by rbolsius** [comment]
Created issue https://github.com/Microsoft/vscode-markdown-tm-grammar/issues/39 (Syntax highlighting for reference link definitions broken) for the problem with reference link definitions that contain characters other than alphanumeric or underscore.

**Comment by irvnriir** [comment]
Can this be made optional? So when disabled, the highlighting would require that `[<<..>>]` would be followed by `(`, `[` or `:`, to not be just text.

![image](https://github.com/microsoft/vscode-markdown-tm-grammar/assets/13949704/32aae1fe-cb6e-4222-8420-8b6d39531a72)
