### ISSUE TITLE
bold can't get highlight

### ISSUE THREAD

**Issue by linsui** [Microsoft/vscode-markdown-tm-grammar#22]
```
a**sdsd**
a **sdsd**
```
The first get highlight but the second doesn't

**Comment by neilsustc** [comment]
I guess you mean the opposite.

![image](https://user-images.githubusercontent.com/7588612/43991922-d3e3b58a-9da8-11e8-80db-30282042c2e3.png)

Version: 1.26.0-insider
Commit: 207ace21dfec3dccab52f1296a3880ac7644c978
Date: 2018-08-10T06:49:26.279Z
