### ISSUE TITLE
Incorrect highlight \`\`

### ISSUE THREAD

**Issue by linsui** [microsoft/vscode-markdown-tm-grammar#28]
<img width="42" alt="default" src="https://user-images.githubusercontent.com/36977733/44723541-de243800-ab02-11e8-932e-d9e9ce87c8e1.PNG">
<img width="25" alt="default" src="https://user-images.githubusercontent.com/36977733/44723556-f005db00-ab02-11e8-9f08-c9ea80814248.PNG">

**Comment by msftrncs** [comment]
Is this still an issue?   I don't see what is wrong.  Maybe its been fixed since this issue was opened?

**Comment by linsui** [comment]
It's is not a code block but be hightlighted as a code block inline.

**Comment by msftrncs** [comment]
I am getting it scoped as two escape characters.

![image](https://user-images.githubusercontent.com/26179051/63676002-ae5c4e80-c7af-11e9-8c71-b0bbc934899a.png)

**Comment by linsui** [comment]
You are right, thanks!
