### ISSUE TITLE
Bold+italic style in markdown is styled as just bold in code view

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-markdown-tm-grammar#3]
_From @Tyriar on March 10, 2016 5:54_

The last link should also be in italics.

![image](https://cloud.githubusercontent.com/assets/2193314/13660712/64e6799a-e641-11e5-83f0-3c454be23d55.png)

_Copied from original issue: Microsoft/vscode#3948_

**Comment by mjbvz** [comment]
_From @bpasero on June 16, 2016 16:9_

Please reopen if you still see this with our new markdown extension.

**Comment by mjbvz** [comment]
_From @freebroccolo on May 26, 2017 23:16_

@Tyriar @bpasero Was this ever fixed? It seems to be broken as of `1.12.2`.

However, instead of only seeing bold for the last line, I'm only seeing italic.

Furthermore, in one of my own extensions that used bold + italic highlighting, it seems only one of those styles will apply at a time. It definitely worked properly sometime last year but it's not working now.

**Comment by mjbvz** [comment]
_From @Tyriar on May 27, 2017 1:56_

This has indeed regressed.

![image](https://cloud.githubusercontent.com/assets/2193314/26517024/1548def8-4245-11e7-91dd-714e6eaaafcc.png)

**Comment by mjbvz** [comment]
_From @freebroccolo on September 7, 2017 4:14_

Any news on this?

**Comment by ShalokShalom** [comment]
Ähm, why marked as spam? 

And why closed?

**Comment by icecream17** [comment]
It still doesn't work
![image](https://user-images.githubusercontent.com/58114641/108246904-9ac94400-7117-11eb-9119-0aa35644105b.png)

**Comment by izumitelj** [comment]
I'm experiencing the same issue. Why is this issue closed?

**Comment by icecream17** [comment]
To prevent spam, react "confused" on this comment.
I'll update this comment sooner or later after the confuseds, which technically also "updates" this issue

Confused reactions: 1

**Comment by quanticle** [comment]
Could we reopen this issue? I'm still seeing this issue in a markdown file:
```
# Test

_italic **bold** italic italic_
*italic **bold** italic*
```

<img width="269" alt="Screen Shot 2022-01-05 at 4 33 29 PM" src="https://user-images.githubusercontent.com/122136/148299173-ba9e8f4b-9f6a-49f9-b903-67fcc44d5e42.png">

This is present on the latest Insider's Build of Visual Studio Code:
```
Version: 1.64.0-insider (Universal)
Commit: 990ad4044032b05c0ebf0f67f800c5845baad4c7
Date: 2022-01-04T05:14:46.209Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

**Comment by icecream17** [comment]
The commit that "fixes" the issue adds two tests?

**Comment by thomasabishop** [comment]
Why was this closed? It is not fixed.
