### ISSUE TITLE
Square brackets highlight

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode-markdown-tm-grammar#34]
![image](https://user-images.githubusercontent.com/7588612/46576503-e81f3d80-c9c2-11e8-8a4c-10473671bef4.png)

Version: 1.28.0-insider (user setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-03T12:44:29.343Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by mjbvz** [comment]
Should be fixed by #35
