### ISSUE TITLE
jsonc isn't recognized as a valid language identifier

### ISSUE THREAD

**Issue by connorshea** [Microsoft/vscode-markdown-tm-grammar#37]
When including a code block with the language identifier `jsonc`, the JSON isn't highlighted correctly (in fact, the default `json` identifier allows comments, which shouldn't be valid).

<img width="527" alt="screen shot 2018-11-01 at 5 08 55 pm" src="https://user-images.githubusercontent.com/2977353/47885053-d598f800-ddf8-11e8-98f4-b5b9fa513a6a.png">

GitHub recognizes `json` and `jsonc` as separate languages when using markdown, for example:

A bit of JSON with comments, using the identifier `json`:
```json
{ 
  // This is json
  "json": true
}
```

A bit of JSON with comments, using the identifier `jsonc`:
```jsonc
{ 
  // This is jsonc
  "json": true
}
```

As a quick fix, you could just add jsonc to [this line](https://github.com/Microsoft/vscode-markdown-tm-grammar/blob/ee6a11d0bbbe8ef6bcf8e664f446c00fb14212f2/build.js#L42) as one of the identifiers in `build.js`, but that isn't ideal.

Alternatively, VS Code already supports "JSON with Comments" out of the box, so you should be able to add a new identifier set for it (assuming this extension gets its grammars for other languages this way?).

**Comment by mjbvz** [comment]
That's the proper fix. Want to submit a PR?

**Comment by mjbvz** [comment]
The most correct fix is to create a new block for jsconc. The scope/source for `jsonc` is `source.json.comments`

**Comment by connorshea** [comment]
I'll open a PR then :)
