### ISSUE TITLE
Add syntax highlighting for plsql

### ISSUE THREAD

**Issue by user-name-is-taken** [microsoft/vscode-markdown-tm-grammar#46]
Something like this should work.

```PLSQL
DECLARE
  lv_ord_date DATE;
BEGIN
---- pl/SQL EXECUTABLE STATEMENTS ----
END;
```

**Comment by mjbvz** [comment]
Actually, this should probably be up to the extension that contributes the plsql. See https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example for how to do this
