### ISSUE TITLE
Angle brackets surrounding html tags inside other styles are colored incorrectly

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode-markdown-tm-grammar#48]
If an HTML tag is present inside another style, such as bold, the HTML tag's text is highlighted fine, but the brackets surrounding the tag are highlighted incorrectly:

Example:
```markdown
**abcdefg<kbd>hij</kbd>**
```
Which renders as:
![image](https://user-images.githubusercontent.com/2294248/63031497-075be680-be82-11e9-900f-e6ea0f2c68b5.png)

In that screenshot, `<`, `>`, and `</` should be white.

**Comment by mjbvz** [comment]
Closing as the parsing of this seems right but themes may need to be updated to style this case correctly
