### ISSUE TITLE
Markdown Highlighting: Uppercase and Unknown Tags

### ISSUE THREAD

**Issue by karlhorky** [microsoft/vscode-markdown-tm-grammar#49]
**Note:** This was previously opened in microsoft/vscode#79119

The Markdown syntax highlighting grammar doesn't recognize valid uppercase HTML tags or unknown tags (such as web components):

![Screen Shot 2019-08-14 at 15 57 10](https://user-images.githubusercontent.com/1935696/63026993-6e8e9080-beac-11e9-8605-47b9aea6902e.png)

Compare that with the HTML grammar highlighting, which would be the preferable output:

![Screen Shot 2019-08-14 at 16 02 35](https://user-images.githubusercontent.com/1935696/63027367-202dc180-bead-11e9-9ab9-2693f7385b48.png)

---

Background: In @silvenon's [MDX extension](https://github.com/silvenon/vscode-mdx), I would like React component highlighting to work properly inline (see silvenon/vscode-mdx#9).

While this wouldn't get us all of the way there, it would at least be a step in the right direction (and would also benefit normal Markdown users).

---

Potentially related (HTML Textmate Grammar fix for custom HTML tags):

https://github.com/textmate/html.tmbundle/issues/92
https://github.com/microsoft/vscode/commit/cfc2a2212de9ea10943af58ebd1817a5ad196463

**Comment by karlhorky** [comment]
I've copied this from microsoft/vscode#79119. Will close whichever one is invalid.

**Comment by mjbvz** [comment]
Thanks. Please open separate issues if you notice any other cases for html tag still not working properly in the next VS Code insiders build

**Comment by karlhorky** [comment]
@mjbvz Thanks, https://github.com/microsoft/vscode-markdown-tm-grammar/commit/67b9b347e34950f3e63ec923e20ac620ffa2ddd7 seems to solve the first part of the request - the uppercase tags.

About the unknown tags - such as web components (custom elements) - is this something that can be supported as well? Should I open that as a new issue for discussion?

**Comment by mjbvz** [comment]
Yes and you’d need to be the one to fix that since it had not been requested for normal md by anyone.
