### ISSUE TITLE
Running tests changes the files the tests are comparing results to

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode-markdown-tm-grammar#51]
It appears as though running the test suite twice will always result in successful test results, as running the tests modified the files that the results are being compared to.

The test suite should be reorganized such that there is a `colorize-expected-results` directory and a gitignored `colorize-results` directory or similar that can be used to inspect the results.

**Comment by mjbvz** [comment]
This is the design. I use it to inspect the changed results in an normal editor instead of in console output
