### ISSUE TITLE
'syntaxes' directory should possibly be gitignored

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode-markdown-tm-grammar#52]
I'm not 100% sure about this one, but it appears that, since the `markdown.tmLanguage` file is automatically generated, the entire `syntaxes` directory should not be committed to the repository. It just duplicates the information in `markdown.tmLanguage.base.yaml` in a different format.

If I'm incorrect about this feel free to close immediately.

**Comment by mjbvz** [comment]
VS code pull in this generated file so it must be checked in
