### ISSUE TITLE
Markdown behaviour incorrect when underscores are used within quoted attribute values

### ISSUE THREAD

**Issue by codingthat** [microsoft/vscode-markdown-tm-grammar#72]
- VSCode Version: 1.44.0
- OS Version: Linux Mint 19.3 x64 (5.3.0-45-generic)

Steps to Reproduce:

1. Save a file as test.md with the following content:

``` md
_This is a sample sentence including a [link](https://github.com){:target="_blank"} with an underscore in a quoted attribute._

_This is a sample sentence including a [link](https://github.com){:target="somethingelse"} without an underscore in a quoted attribute._
```

2. Note the difference between the styling of the two lines.  Both should be fully italicized, but only the second one is:

![image](https://user-images.githubusercontent.com/26723818/78895480-3bb68f80-7a6f-11ea-8100-31e4412f56cb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
`[link](https://github.com){:target="_blank"} ` looks like an extension to markdown. What markdown engine are you using that supports that?

**Comment by codingthat** [comment]
Oh, dang, you're right.  Sorry, I use it so much I forgot that's not supported by vanilla Markdown.  It's [Kramdown](https://github.com/gettalong/kramdown), popular in the Ruby world.

**Comment by mjbvz** [comment]
Ok, I'm going to close this issue then since our built-in markdown grammar tries to target [common mark](https://commonmark.org)

I believe an extension could add this using an [injection grammar](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars)
