### ISSUE TITLE
Add syntax highlight for Markdown preview new language.

### ISSUE THREAD

**Issue by Serhioromano** [microsoft/vscode-markdown-tm-grammar#79]
I have created extension for Structured Text language support language ID `st`. I also added prismjs language highlights language ID `iecst`. 

How to mak eit so that in markdown preview in a code block, syntax was highlighted?

**Comment by mjbvz** [comment]
See https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example for how your extension can contribute this

**Comment by Serhioromano** [comment]
Thanks @mjbvz that works fine. It does highlight code in markdown source.

![2020-10-13_13-43-10](https://user-images.githubusercontent.com/650741/95830832-16764700-0d5a-11eb-973e-d3cf16fad795.png)

How I can make it to be highlighted in Markdown preview? Second rectangle.

**Comment by mjbvz** [comment]
This is not currently supported since the preview uses [highlight.js](https://highlightjs.org)
