### ISSUE TITLE
Support multiple tags on fenced code blocks in Markdown documents

### ISSUE THREAD

**Issue by danieleades** [microsoft/vscode-markdown-tm-grammar#90]
There are various applications for multiple tags on fenced code blocks. These are comma-separated, where the first tag specifies the language and subsequent tags have special meaning in specific contexts.

For example, rust code blocks use the tag 'rust'. as in-
````
```rust
fn foo(bar: &Bar) {
// ...
}
```
````

tools such as [doctest](https://docs.rs/doc-comment/0.3.3/doc_comment/macro.doctest.html) allow rust code blocks in markdown documents to be tested, to ensure documentation is aligned with code. Rust fenced code blocks accept additional parameters, such as 'no_run'. as in-

````
```rust,no_run
fn foo(bar: &Bar) {
// ...
}
```
````

with the extra annotation, this is no longer highlighted in Code in the markdown document.

github renders it just fine, however-

```rust,no_run
fn foo(bar: &Bar) {
// ...
}
```

I suspect Code can just ignore any annotations after the first comma

**Comment by mjbvz** [comment]
@danieleades This repository contains the grammar we use to highly markdown code

**Comment by danieleades** [comment]
Hi @mjbvz any tips on how this works?

- `markdown.tmLanguage.base.yaml` seems to define the grammer, but definitions of the fenced code blocks look to be dynamically inserted into the template.
- that insert is defined in `build.js` - `{ name: 'rust', language: 'rust', identifiers: ['rust', 'rs', '\\{\\.rust.+?\\}'], source: 'source.rust' },`
   - where is `source.rust` coming from?

**Comment by mjbvz** [comment]
Take a look at the begin pattern here: https://github.com/microsoft/vscode-markdown-tm-grammar/blob/de428fd70cb101c0858996dfca9a462418a04c43/build.js#L85

It already has support for a few other language name variants, such as `rust:bla`

**Comment by danieleades** [comment]
thanks @mjbvz 
i'm testing this regex here - https://regex101.com/r/93jDQr/1
but can't get it to work. any ideas?
