### ISSUE TITLE
Timeout of issues-vs-101485.md test

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-markdown-tm-grammar#98]
See 7aa9352031c7325c9447fb9f3df42c15c547328e where the CI fails on windows

![image](https://user-images.githubusercontent.com/12758612/136676158-75b5c400-488d-495d-834e-d86153bab01c.png)

**Comment by mjbvz** [comment]
Fixed by bf8fe87ba200976339e55263b3be0be6d4d2e51f
